#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuitarFLVW.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="wsim")]
	public partial class SessionDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    partial void InsertTRAINING(TRAINING instance);
    partial void UpdateTRAINING(TRAINING instance);
    partial void DeleteTRAINING(TRAINING instance);
    #endregion
		
		public SessionDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["wsimConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SessionDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SessionDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SessionDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SessionDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
		
		public System.Data.Linq.Table<TRAINING> TRAININGs
		{
			get
			{
				return this.GetTable<TRAINING>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERS")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Usr_id;
		
		private string _Usr_Name;
		
		private string _Usr_Password;
		
		private System.Nullable<System.DateTime> _Usr_BirthDay;
		
		private System.Nullable<int> _Usr_Damage;
		
		private System.Nullable<int> _Usr_TotalTrainingSessions;
		
		private System.Nullable<int> _Usr_TotalDamageDone;
		
		private System.Nullable<int> _Usr_Streng;
		
		private EntityRef<TRAINING> _TRAINING;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsr_idChanging(int value);
    partial void OnUsr_idChanged();
    partial void OnUsr_NameChanging(string value);
    partial void OnUsr_NameChanged();
    partial void OnUsr_PasswordChanging(string value);
    partial void OnUsr_PasswordChanged();
    partial void OnUsr_BirthDayChanging(System.Nullable<System.DateTime> value);
    partial void OnUsr_BirthDayChanged();
    partial void OnUsr_DamageChanging(System.Nullable<int> value);
    partial void OnUsr_DamageChanged();
    partial void OnUsr_TotalTrainingSessionsChanging(System.Nullable<int> value);
    partial void OnUsr_TotalTrainingSessionsChanged();
    partial void OnUsr_TotalDamageDoneChanging(System.Nullable<int> value);
    partial void OnUsr_TotalDamageDoneChanged();
    partial void OnUsr_StrengChanging(System.Nullable<int> value);
    partial void OnUsr_StrengChanged();
    #endregion
		
		public USER()
		{
			this._TRAINING = default(EntityRef<TRAINING>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Usr_id
		{
			get
			{
				return this._Usr_id;
			}
			set
			{
				if ((this._Usr_id != value))
				{
					this.OnUsr_idChanging(value);
					this.SendPropertyChanging();
					this._Usr_id = value;
					this.SendPropertyChanged("Usr_id");
					this.OnUsr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr_Name", DbType="NVarChar(50)")]
		public string Usr_Name
		{
			get
			{
				return this._Usr_Name;
			}
			set
			{
				if ((this._Usr_Name != value))
				{
					this.OnUsr_NameChanging(value);
					this.SendPropertyChanging();
					this._Usr_Name = value;
					this.SendPropertyChanged("Usr_Name");
					this.OnUsr_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr_Password", DbType="NVarChar(50)")]
		public string Usr_Password
		{
			get
			{
				return this._Usr_Password;
			}
			set
			{
				if ((this._Usr_Password != value))
				{
					this.OnUsr_PasswordChanging(value);
					this.SendPropertyChanging();
					this._Usr_Password = value;
					this.SendPropertyChanged("Usr_Password");
					this.OnUsr_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr_BirthDay", DbType="DateTime")]
		public System.Nullable<System.DateTime> Usr_BirthDay
		{
			get
			{
				return this._Usr_BirthDay;
			}
			set
			{
				if ((this._Usr_BirthDay != value))
				{
					this.OnUsr_BirthDayChanging(value);
					this.SendPropertyChanging();
					this._Usr_BirthDay = value;
					this.SendPropertyChanged("Usr_BirthDay");
					this.OnUsr_BirthDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr_Damage", DbType="Int")]
		public System.Nullable<int> Usr_Damage
		{
			get
			{
				return this._Usr_Damage;
			}
			set
			{
				if ((this._Usr_Damage != value))
				{
					this.OnUsr_DamageChanging(value);
					this.SendPropertyChanging();
					this._Usr_Damage = value;
					this.SendPropertyChanged("Usr_Damage");
					this.OnUsr_DamageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr_TotalTrainingSessions", DbType="Int")]
		public System.Nullable<int> Usr_TotalTrainingSessions
		{
			get
			{
				return this._Usr_TotalTrainingSessions;
			}
			set
			{
				if ((this._Usr_TotalTrainingSessions != value))
				{
					this.OnUsr_TotalTrainingSessionsChanging(value);
					this.SendPropertyChanging();
					this._Usr_TotalTrainingSessions = value;
					this.SendPropertyChanged("Usr_TotalTrainingSessions");
					this.OnUsr_TotalTrainingSessionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr_TotalDamageDone", DbType="Int")]
		public System.Nullable<int> Usr_TotalDamageDone
		{
			get
			{
				return this._Usr_TotalDamageDone;
			}
			set
			{
				if ((this._Usr_TotalDamageDone != value))
				{
					this.OnUsr_TotalDamageDoneChanging(value);
					this.SendPropertyChanging();
					this._Usr_TotalDamageDone = value;
					this.SendPropertyChanged("Usr_TotalDamageDone");
					this.OnUsr_TotalDamageDoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr_Streng", DbType="Int")]
		public System.Nullable<int> Usr_Streng
		{
			get
			{
				return this._Usr_Streng;
			}
			set
			{
				if ((this._Usr_Streng != value))
				{
					this.OnUsr_StrengChanging(value);
					this.SendPropertyChanging();
					this._Usr_Streng = value;
					this.SendPropertyChanged("Usr_Streng");
					this.OnUsr_StrengChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USER_TRAINING", Storage="_TRAINING", ThisKey="Usr_id", OtherKey="Train_ID", IsUnique=true, IsForeignKey=false)]
		public TRAINING TRAINING
		{
			get
			{
				return this._TRAINING.Entity;
			}
			set
			{
				TRAINING previousValue = this._TRAINING.Entity;
				if (((previousValue != value) 
							|| (this._TRAINING.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRAINING.Entity = null;
						previousValue.USER = null;
					}
					this._TRAINING.Entity = value;
					if ((value != null))
					{
						value.USER = this;
					}
					this.SendPropertyChanged("TRAINING");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRAININGS")]
	public partial class TRAINING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Train_ID;
		
		private System.DateTime _Train_Date;
		
		private System.Nullable<int> _User_ID;
		
		private EntityRef<USER> _USER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTrain_IDChanging(int value);
    partial void OnTrain_IDChanged();
    partial void OnTrain_DateChanging(System.DateTime value);
    partial void OnTrain_DateChanged();
    partial void OnUser_IDChanging(System.Nullable<int> value);
    partial void OnUser_IDChanged();
    #endregion
		
		public TRAINING()
		{
			this._USER = default(EntityRef<USER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Train_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Train_ID
		{
			get
			{
				return this._Train_ID;
			}
			set
			{
				if ((this._Train_ID != value))
				{
					if (this._USER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTrain_IDChanging(value);
					this.SendPropertyChanging();
					this._Train_ID = value;
					this.SendPropertyChanged("Train_ID");
					this.OnTrain_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Train_Date", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Train_Date
		{
			get
			{
				return this._Train_Date;
			}
			set
			{
				if ((this._Train_Date != value))
				{
					this.OnTrain_DateChanging(value);
					this.SendPropertyChanging();
					this._Train_Date = value;
					this.SendPropertyChanged("Train_Date");
					this.OnTrain_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="Int")]
		public System.Nullable<int> User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USER_TRAINING", Storage="_USER", ThisKey="Train_ID", OtherKey="Usr_id", IsForeignKey=true)]
		public USER USER
		{
			get
			{
				return this._USER.Entity;
			}
			set
			{
				USER previousValue = this._USER.Entity;
				if (((previousValue != value) 
							|| (this._USER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USER.Entity = null;
						previousValue.TRAINING = null;
					}
					this._USER.Entity = value;
					if ((value != null))
					{
						value.TRAINING = this;
						this._Train_ID = value.Usr_id;
					}
					else
					{
						this._Train_ID = default(int);
					}
					this.SendPropertyChanged("USER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
